---
# ··············································································
    # ###  locale-fix | Ensure a locale exists.
# ··············································································

- name      : Fix locale es_CO.UTF-8
  locale_gen:
    name    : es_CO.UTF-8
    state   : present

- name      : Fix locale en_US.UTF-8
  locale_gen:
    name    : en_US.UTF-8
    state   : present

- name      : Fix locale ja_jp.utf-8
  locale_gen:
    name    : ja_JP.UTF-8
    state   : present
